In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, cdist
import numpy as np
import math
import datetime as dt
from datetime import timedelta
import itertools
from collections import defaultdict
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "../tests")))

In [2]:
# sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))
import filters
import daphmeIO as loader
import constants as constants
import stop_detection_modified as SD

In [3]:
path = '../data/sample4/'

traj_cols = {'user_id':'user_id',
             'latitude':'dev_lat',
             'longitude':'dev_lon',
             'datetime':'local_datetime'}

df = loader.from_file(path, traj_cols=traj_cols, format='csv')

In [4]:
df = filters.to_projection(df, latitude='dev_lat', longitude='dev_lon')

In [5]:
df['timestamp'] = df['local_datetime'].astype('int64') // 10**9

In [6]:
df

,user_id,dev_lat,dev_lon,local_datetime,x,y,timestamp
0,wizardly_joliot,38.321711,-36.667334,2024-01-01 14:29:00,-4.081789e+06,4.624973e+06,1704119340
1,wizardly_joliot,38.321676,-36.667365,2024-01-01 14:35:00,-4.081792e+06,4.624968e+06,1704119700
2,wonderful_swirles,38.321017,-36.667869,2024-01-01 15:06:00,-4.081849e+06,4.624874e+06,1704121560
3,youthful_galileo,38.321625,-36.666612,2024-01-01 08:47:00,-4.081709e+06,4.624961e+06,1704098820
4,youthful_galileo,38.321681,-36.666841,2024-01-01 09:59:00,-4.081734e+06,4.624969e+06,1704103140
...,...,...,...,...,...,...,...
25830,angry_spence,38.320399,-36.667438,2024-01-15 07:23:00,-4.081801e+06,4.624787e+06,1705303380
25831,angry_spence,38.320413,-36.667469,2024-01-15 07:29:00,-4.081804e+06,4.624789e+06,1705303740
25832,angry_spence,38.320384,-36.667455,2024-01-15 07:33:00,-4.081802e+06,4.624785e+06,1705303980
25833,angry_spence,38.320349,-36.667473,2024-01-15 07:39:00,-4.081804e+06,4.624780e+06,1705304340


In [7]:
sample_user_df = df[df['user_id'] == "youthful_galileo"]

In [8]:
time_thresh = 10
dist_thresh = 5
min_pts = 3

In [9]:
SD.temporal_dbscan(sample_user_df, time_thresh, dist_thresh, min_pts, traj_cols=traj_cols)

Time differences (seconds): 
[[      0    4320    5040 ... 1192080 1194780 1196400]
 [   4320       0     720 ... 1187760 1190460 1192080]
 [   5040     720       0 ... 1187040 1189740 1191360]
 ...
 [1192080 1187760 1187040 ...       0    2700    4320]
 [1194780 1190460 1189740 ...    2700       0    1620]
 [1196400 1192080 1191360 ...    4320    1620       0]]
Time pairs (indices): (array([  2,   8,   8,   9,  16,  16,  16,  17,  17,  18,  20,  22,  25,
        25,  25,  26,  26,  27,  29,  36,  36,  37,  40,  42,  42,  43,
        43,  43,  44,  44,  45,  45,  46,  49,  51,  53,  56,  57,  58,
        59,  62,  64,  66,  66,  67,  69,  70,  70,  71,  72,  73,  75,
        75,  76,  81,  83,  83,  84,  85,  86,  86,  86,  87,  87,  88,
        92,  93,  98, 105, 107, 110, 111, 113, 117, 117, 118, 121, 121,
       122, 124, 127, 131, 133, 136, 143, 144, 144, 145, 145, 146, 147,
       147, 147, 148, 148, 149, 151, 151, 152, 152, 153, 155, 157, 157,
       158, 160, 170, 170, 171, 172,

,cluster,core
timestamp,,
1704098820,-5,-5
1704103140,-5,-5
1704103860,-5,-5
1704104100,-5,-5
1704105360,-5,-5
...,...,...
1705290780,-5,-5
1705290840,-5,-5
1705290900,-5,-5


In [ ]:
neighbors = SD.find_neighbors(sample_user_df, time_thresh, dist_thresh, long_lat=False, datetime=False, traj_cols=traj_cols)

In [ ]:
dur_min = 100
dt_max = 120
delta_roam = 10

In [ ]:
SD.lachesis(sample_user_df, dur_min, dt_max, delta_roam, traj_cols=traj_cols, complete_output=False)